# Generated by Django 5.2.12 on 2026-04-12 03:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_browsehistory"),
    ]

    operations = [
        migrations.DeleteModel(
            name="FavoriteRecipe",
        ),
    ]
