# Generated by Django 5.2.12 on 2026-04-10 03:53

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipe", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="recipe",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "菜谱",
                "verbose_name_plural": "菜谱",
            },
        ),
        migrations.RemoveField(
            model_name="recipe",
            name="cooking_time",
        ),
        migrations.RemoveField(
            model_name="recipe",
            name="ingredients",
        ),
        migrations.RemoveField(
            model_name="recipe",
            name="name",
        ),
        migrations.RemoveField(
            model_name="recipe",
            name="steps",
        ),
        migrations.AddField(
            model_name="recipe",
            name="author",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="published_recipes",
                to=settings.AUTH_USER_MODEL,
                verbose_name="发布用户",
            ),
        ),
        migrations.AddField(
            model_name="recipe",
            name="category",
            field=models.CharField(
                blank=True, default="", max_length=50, verbose_name="菜系"
            ),
        ),
        migrations.AddField(
            model_name="recipe",
            name="comments",
            field=models.PositiveIntegerField(default=0, verbose_name="评论数"),
        ),
        migrations.AddField(
            model_name="recipe",
            name="cook_time",
            field=models.CharField(
                blank=True, default="", max_length=30, verbose_name="耗时"
            ),
        ),
        migrations.AddField(
            model_name="recipe",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="创建时间",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="recipe",
            name="description",
            field=models.TextField(blank=True, default="", verbose_name="菜谱简介"),
        ),
        migrations.AddField(
            model_name="recipe",
            name="difficulty",
            field=models.CharField(
                blank=True, default="", max_length=20, verbose_name="难度"
            ),
        ),
        migrations.AddField(
            model_name="recipe",
            name="favorites",
            field=models.PositiveIntegerField(default=0, verbose_name="收藏数"),
        ),
        migrations.AddField(
            model_name="recipe",
            name="image",
            field=models.URLField(blank=True, default="", verbose_name="图片链接"),
        ),
        migrations.AddField(
            model_name="recipe",
            name="is_recommended",
            field=models.BooleanField(default=False, verbose_name="是否推荐"),
        ),
        migrations.AddField(
            model_name="recipe",
            name="likes",
            field=models.PositiveIntegerField(default=0, verbose_name="点赞数"),
        ),
        migrations.AddField(
            model_name="recipe",
            name="servings",
            field=models.CharField(
                blank=True, default="2人份", max_length=20, verbose_name="份量"
            ),
        ),
        migrations.AddField(
            model_name="recipe",
            name="title",
            field=models.CharField(default="", max_length=100, verbose_name="菜谱名称"),
        ),
        migrations.AddField(
            model_name="recipe",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="更新时间"),
        ),
        migrations.AddField(
            model_name="recipe",
            name="views",
            field=models.PositiveIntegerField(default=0, verbose_name="浏览量"),
        ),
        migrations.AlterModelTable(
            name="recipe",
            table="recipe",
        ),
        migrations.CreateModel(
            name="RecipeIngredient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(default="", max_length=100, verbose_name="食材名称"),
                ),
                (
                    "amount",
                    models.CharField(
                        blank=True, default="", max_length=50, verbose_name="用量"
                    ),
                ),
                (
                    "unit",
                    models.CharField(
                        blank=True, default="", max_length=20, verbose_name="单位"
                    ),
                ),
                (
                    "recipe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ingredients",
                        to="recipe.recipe",
                        verbose_name="所属菜谱",
                    ),
                ),
            ],
            options={
                "verbose_name": "菜谱食材",
                "verbose_name_plural": "菜谱食材",
                "db_table": "recipe_ingredient",
            },
        ),
        migrations.CreateModel(
            name="RecipeStep",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "step_no",
                    models.PositiveIntegerField(default=1, verbose_name="步骤序号"),
                ),
                ("content", models.TextField(default="", verbose_name="步骤内容")),
                (
                    "time_text",
                    models.CharField(
                        blank=True, default="", max_length=30, verbose_name="步骤耗时"
                    ),
                ),
                (
                    "recipe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="steps",
                        to="recipe.recipe",
                        verbose_name="所属菜谱",
                    ),
                ),
            ],
            options={
                "verbose_name": "菜谱步骤",
                "verbose_name_plural": "菜谱步骤",
                "db_table": "recipe_step",
                "ordering": ["step_no"],
            },
        ),
    ]
