# Generated by Django 5.2.12 on 2026-04-10 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipe", "0002_alter_recipe_options_remove_recipe_cooking_time_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="recipes/", verbose_name="菜谱图片"
            ),
        ),
    ]
