# Generated by Django 5.2.12 on 2026-04-16 02:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipe", "0004_recipefavorite_recipelike"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="recipe",
            options={},
        ),
        migrations.RemoveField(
            model_name="recipe",
            name="author",
        ),
        migrations.RemoveField(
            model_name="recipe",
            name="comments",
        ),
        migrations.RemoveField(
            model_name="recipe",
            name="updated_at",
        ),
        migrations.AddField(
            model_name="recipe",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="submitted_recipes",
                to=settings.AUTH_USER_MODEL,
                verbose_name="提交用户",
            ),
        ),
        migrations.AddField(
            model_name="recipe",
            name="review_comment",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="审核意见"
            ),
        ),
        migrations.AddField(
            model_name="recipe",
            name="review_status",
            field=models.CharField(
                choices=[
                    ("pending", "待审核"),
                    ("approved", "审核通过"),
                    ("rejected", "审核驳回"),
                ],
                default="approved",
                max_length=20,
                verbose_name="审核状态",
            ),
        ),
        migrations.AddField(
            model_name="recipe",
            name="reviewed_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="审核时间"),
        ),
        migrations.AddField(
            model_name="recipe",
            name="source",
            field=models.CharField(
                choices=[("admin", "管理员创建"), ("user", "用户投稿")],
                default="admin",
                max_length=20,
                verbose_name="来源",
            ),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="category",
            field=models.CharField(blank=True, max_length=100, verbose_name="菜系"),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="cook_time",
            field=models.CharField(blank=True, max_length=50, verbose_name="耗时"),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="description",
            field=models.TextField(blank=True, verbose_name="菜谱简介"),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="difficulty",
            field=models.CharField(blank=True, max_length=50, verbose_name="难度"),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="favorites",
            field=models.IntegerField(default=0, verbose_name="收藏数"),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="likes",
            field=models.IntegerField(default=0, verbose_name="点赞数"),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="servings",
            field=models.CharField(default="2人份", max_length=50, verbose_name="份量"),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="title",
            field=models.CharField(max_length=255, verbose_name="菜谱名称"),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="views",
            field=models.IntegerField(default=0, verbose_name="浏览量"),
        ),
        migrations.AlterModelTable(
            name="recipe",
            table=None,
        ),
    ]
