# Generated by Django 5.2.12 on 2026-04-17 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipe", "0005_alter_recipe_options_remove_recipe_author_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="rejection_notice_read",
            field=models.BooleanField(default=True, verbose_name="驳回通知是否已读"),
        ),
    ]
