from django.urls import path
from .views import (
    api_recommend_recipes_db,
    api_recipe_detail_db,
    api_recipe_list_db,
    api_hot_recipes_db,
    api_toggle_recipe_favorite,
    api_toggle_recipe_like,
    api_recipe_favorite_list,
    api_remove_recipe_favorite,
    api_submit_recipe,
    api_my_recipe_submissions,
    api_mark_submission_notifications_read,
    api_submission_detail,
    api_resubmit_recipe,
    api_recipe_comments,
    api_add_recipe_comment,
    api_delete_recipe_comment,
)

urlpatterns = [
    path('recipes/recommend/', api_recommend_recipes_db),
    path('recipes/<int:recipe_id>/', api_recipe_detail_db),
    path('recipes/all/', api_recipe_list_db),
    path('recipes/hot/', api_hot_recipes_db),
    path('recipes/favorite/toggle/', api_toggle_recipe_favorite),
    path('recipes/like/toggle/', api_toggle_recipe_like),
    path('recipes/favorites/', api_recipe_favorite_list),
    path('recipes/favorite/remove/', api_remove_recipe_favorite),
    path('recipes/submit/', api_submit_recipe),
    path('recipes/my-submissions/', api_my_recipe_submissions),
    path('recipes/my-submissions/', api_my_recipe_submissions),
    path('recipes/my-submissions/read/', api_mark_submission_notifications_read),
    path('recipes/my-submissions/<int:recipe_id>/', api_submission_detail),
    path('recipes/my-submissions/<int:recipe_id>/resubmit/', api_resubmit_recipe),
    path('recipes/<int:recipe_id>/comments/', api_recipe_comments),
    path('recipes/<int:recipe_id>/comments/add/', api_add_recipe_comment),
    path('recipes/comments/<int:comment_id>/delete/', api_delete_recipe_comment),
]